# Generated by Django 3.2.9 on 2023-05-29 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario_ventas',
            old_name='tienda_id',
            new_name='tienda',
        ),
    ]
