# Generated by Django 3.2.9 on 2023-04-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inventario_ventas',
        ),
    ]
