# Generated by Django 3.2.9 on 2023-05-29 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0003_auto_20230528_2202'),
        ('ArqueoCaja', '0001_initial'),
        ('Inventario', '0002_rename_tienda_id_inventario_ventas_tienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_ventas',
            name='arqueo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ArqueoCaja.arqueo'),
        ),
        migrations.AlterField(
            model_name='inventario_ventas',
            name='tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tienda'),
        ),
    ]
