# Generated by Django 3.2.9 on 2023-05-31 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArqueoCaja', '0002_auto_20230530_2358'),
        ('Inventario', '0003_auto_20230528_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_ventas',
            name='arqueo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ArqueoCaja.arqueo'),
        ),
    ]
