# Generated by Django 3.2.9 on 2023-05-31 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_alter_inventario_ventas_arqueo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario_ventas',
            old_name='arqueo',
            new_name='arqueo_id',
        ),
        migrations.RenameField(
            model_name='inventario_ventas',
            old_name='tienda',
            new_name='tienda_id',
        ),
    ]
