# Generated by Django 3.2.9 on 2023-05-31 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0004_auto_20230530_2358'),
        ('ArqueoCaja', '0002_auto_20230530_2358'),
        ('Inventario', '0006_auto_20230531_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_ventas',
            name='arqueo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ArqueoCaja.arqueo'),
        ),
        migrations.AlterField(
            model_name='inventario_ventas',
            name='tienda_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tienda'),
        ),
    ]
