# Generated by Django 3.2.9 on 2023-05-31 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0007_auto_20230531_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario_ventas',
            old_name='arqueo_id',
            new_name='arqueo',
        ),
        migrations.RenameField(
            model_name='inventario_ventas',
            old_name='tienda_id',
            new_name='tienda',
        ),
    ]
