# Generated by Django 3.2.9 on 2023-06-17 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0004_auto_20230530_2358'),
        ('ArqueoCaja', '0010_auto_20230617_0139'),
        ('Inventario', '0008_auto_20230531_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario_ventas',
            name='arqueo',
        ),
        migrations.RemoveField(
            model_name='inventario_ventas',
            name='tienda',
        ),
        migrations.AddField(
            model_name='inventario_ventas',
            name='arqueo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ArqueoCaja.arqueo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario_ventas',
            name='tienda_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tienda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventario_ventas',
            name='created',
            field=models.DateField(),
        ),
    ]
