# Generated by Django 3.2.9 on 2023-06-21 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArqueoCaja', '0016_alter_arqueo_procesado'),
        ('Inventario', '0011_auto_20230620_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario_ventas',
            name='arqueo_id',
        ),
        migrations.AddField(
            model_name='inventario_ventas',
            name='arqueo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ArqueoCaja.arqueo'),
        ),
    ]
