# Generated by Django 3.2.9 on 2023-06-21 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ingresos', '0001_initial'),
        ('Inventario', '0012_auto_20230620_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario_ventas',
            name='arqueo',
        ),
        migrations.AddField(
            model_name='inventario_ventas',
            name='venta_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ingresos.ventas'),
            preserve_default=False,
        ),
    ]
