# Generated by Django 3.2.9 on 2023-06-21 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ingresos', '0001_initial'),
        ('Inventario', '0014_alter_inventario_ventas_venta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_ventas',
            name='venta_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ingresos.ventas'),
        ),
    ]
