# Generated by Django 3.2.9 on 2023-06-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0015_alter_inventario_ventas_venta_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario_ventas',
            name='venta_id',
        ),
    ]
