# Generated by Django 3.2.9 on 2023-06-20 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProyectoWebAC', '0004_auto_20230530_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ef_bs', models.CharField(max_length=10)),
                ('td_bs', models.CharField(max_length=10)),
                ('tc_bs', models.CharField(max_length=10)),
                ('pm_bs', models.CharField(max_length=10)),
                ('nc_bs', models.CharField(max_length=10)),
                ('ti_bs', models.CharField(max_length=20)),
                ('ef_usd', models.CharField(max_length=10)),
                ('tc_usd', models.CharField(max_length=10)),
                ('td_usd', models.CharField(max_length=10)),
                ('pm_usd', models.CharField(max_length=10)),
                ('nc_usd', models.CharField(max_length=10)),
                ('ti_usd', models.CharField(max_length=20)),
                ('conversion_usd', models.CharField(max_length=20)),
                ('nota', models.CharField(max_length=300)),
                ('tif', models.CharField(max_length=30)),
                ('created', models.DateField()),
                ('update', models.DateField(auto_now_add=True)),
                ('caja_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.caja')),
                ('tasa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tasa')),
                ('tienda_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tienda')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
    ]
