# Generated by Django 3.2.9 on 2023-07-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingresos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='procesado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
