# Generated by Django 4.2.4 on 2023-12-22 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0007_tasadolar_tasaeuro_delete_tasa'),
        ('Ingresos', '0003_remove_ventas_tasa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='tasaDolar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tasadolar'),
            preserve_default=False,
        ),
    ]
