# Generated by Django 4.2.4 on 2024-01-29 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ingresos', '0004_ventas_tasadolar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='tasaDolar',
        ),
    ]
