# Generated by Django 3.2.9 on 2023-02-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(max_length=20)),
                ('rif', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=30)),
                ('telf', models.CharField(max_length=30)),
                ('redes', models.CharField(max_length=30)),
                ('n_caja', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('ci', models.CharField(max_length=12)),
                ('cargo', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
