# Generated by Django 3.2.9 on 2023-05-29 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='usuario_id',
        ),
    ]
