# Generated by Django 3.2.9 on 2023-05-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0002_remove_tienda_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
