# Generated by Django 3.2.9 on 2023-02-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0002_auto_20230202_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisas',
            name='tasa_dolar',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='divisas',
            name='tasa_euro',
            field=models.FloatField(),
        ),
    ]
