# Generated by Django 3.2.9 on 2023-02-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0003_auto_20230202_0437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divisas',
            old_name='tasa_dolar',
            new_name='tasaDolar',
        ),
        migrations.RenameField(
            model_name='divisas',
            old_name='tasa_euro',
            new_name='tasaEuro',
        ),
    ]
