# Generated by Django 3.2.9 on 2023-05-31 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0003_auto_20230528_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='codigo_caja',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='caja',
            name='tienda_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tienda'),
        ),
    ]
