# Generated by Django 4.2.4 on 2023-12-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0005_comunicado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caja',
            old_name='tienda_id',
            new_name='tienda',
        ),
        migrations.RenameField(
            model_name='tasa',
            old_name='Dolar',
            new_name='tasa_eur',
        ),
        migrations.RenameField(
            model_name='tasa',
            old_name='Euro',
            new_name='tasa_usd',
        ),
        migrations.AddField(
            model_name='tienda',
            name='nif',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
