# Generated by Django 3.2.9 on 2023-04-13 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0005_tienda_gerente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='gerente',
        ),
    ]
