# Generated by Django 4.2.4 on 2023-12-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArqueoCaja', '0022_remove_arqueo_tasa'),
        ('Ingresos', '0003_remove_ventas_tasa_id'),
        ('ProyectoWebAC', '0006_rename_tienda_id_caja_tienda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasaDolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_usd', models.CharField(max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Divisa',
                'verbose_name_plural': 'Divisas',
            },
        ),
        migrations.CreateModel(
            name='tasaEuro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_eur', models.CharField(max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Divisa',
                'verbose_name_plural': 'Divisas',
            },
        ),
        migrations.DeleteModel(
            name='tasa',
        ),
    ]
