# Generated by Django 3.2.9 on 2023-04-13 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProyectoWebAC', '0006_remove_tienda_gerente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='gerente',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
