# Generated by Django 4.2.4 on 2024-01-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0007_tasadolar_tasaeuro_delete_tasa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasadolar',
            options={'verbose_name': 'Dolar', 'verbose_name_plural': 'Dolars'},
        ),
        migrations.AlterModelOptions(
            name='tasaeuro',
            options={'verbose_name': 'Euro', 'verbose_name_plural': 'Eurs'},
        ),
    ]
