# Generated by Django 3.2.9 on 2023-04-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0007_tienda_gerente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tienda',
            old_name='gerente',
            new_name='id_user',
        ),
    ]
