# Generated by Django 4.2.4 on 2024-01-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0008_alter_tasadolar_options_alter_tasaeuro_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasadolar',
            name='tasa_usd',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='tasaeuro',
            name='tasa_eur',
            field=models.CharField(max_length=6),
        ),
    ]
