# Generated by Django 3.2.9 on 2023-04-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0008_rename_gerente_tienda_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tienda',
            old_name='id_user',
            new_name='gerente',
        ),
    ]
