# Generated by Django 4.2.4 on 2024-01-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0009_alter_tasadolar_tasa_usd_alter_tasaeuro_tasa_eur'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='codigo_tienda',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
