# Generated by Django 4.2.4 on 2024-01-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0010_tienda_codigo_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasadolar',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
