# Generated by Django 3.2.9 on 2023-04-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0010_remove_tienda_gerente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
