# Generated by Django 4.2.4 on 2024-01-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0011_alter_tasadolar_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasadolar',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tasadolar',
            name='update',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasaeuro',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasaeuro',
            name='update',
            field=models.DateField(auto_now_add=True),
        ),
    ]
