# Generated by Django 4.2.4 on 2024-01-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0012_alter_tasadolar_created_alter_tasadolar_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='update',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasadolar',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='update',
            field=models.DateField(auto_now_add=True),
        ),
    ]
