# Generated by Django 3.2.9 on 2023-04-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0012_tienda_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='usuario',
        ),
    ]
