# Generated by Django 4.2.4 on 2024-01-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArqueoCaja', '0029_remove_arqueo_tasadolar'),
        ('Ingresos', '0005_remove_ventas_tasadolar'),
        ('ProyectoWebAC', '0014_tienda_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasaDivisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_usd', models.CharField(max_length=6)),
                ('tasa_eur', models.CharField(max_length=6)),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dolar',
                'verbose_name_plural': 'Dolars',
            },
        ),
        migrations.DeleteModel(
            name='tasaDolar',
        ),
    ]
