# Generated by Django 3.2.9 on 2023-04-13 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProyectoWebAC', '0015_remove_tienda_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.expressions.Value, to='auth.user'),
            preserve_default=False,
        ),
    ]
