# Generated by Django 4.2.4 on 2024-01-29 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArqueoCaja', '0031_remove_arqueo_tasaeuro'),
        ('ProyectoWebAC', '0015_tasadivisa_delete_tasadolar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tasaEuro',
        ),
    ]
