# Generated by Django 4.2.4 on 2024-01-29 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0016_delete_tasaeuro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasadivisa',
            options={'verbose_name': 'Divisa', 'verbose_name_plural': 'Divisas'},
        ),
    ]
