# Generated by Django 3.2.9 on 2023-04-13 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProyectoWebAC', '0018_delete_tienda'),
    ]

    operations = [
        migrations.CreateModel(
            name='tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(max_length=20)),
                ('rif', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=30)),
                ('telf', models.CharField(max_length=30)),
                ('redes', models.CharField(max_length=30)),
                ('n_caja', models.IntegerField(max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
