# Generated by Django 3.2.9 on 2023-04-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0020_remove_tienda_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tienda',
        ),
    ]
