# Generated by Django 3.2.9 on 2023-04-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0021_delete_tienda'),
    ]

    operations = [
        migrations.CreateModel(
            name='tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(max_length=20)),
                ('rif', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=30)),
                ('telf', models.CharField(max_length=30)),
                ('redes', models.CharField(max_length=30)),
                ('n_caja', models.IntegerField(max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
