# Generated by Django 3.2.9 on 2023-04-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0022_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='n_caja',
            field=models.CharField(max_length=2),
        ),
    ]
