# Generated by Django 3.2.9 on 2023-05-26 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProyectoWebAC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingresos_usd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ef', models.CharField(max_length=10)),
                ('tc', models.CharField(max_length=10)),
                ('td', models.CharField(max_length=10)),
                ('pm', models.CharField(max_length=10)),
                ('nc', models.CharField(max_length=10)),
                ('ti_usd', models.CharField(max_length=20)),
                ('conversion', models.CharField(max_length=20)),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now_add=True)),
                ('caja_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.caja')),
                ('tasa_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tasa')),
                ('tienda_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tienda')),
            ],
            options={
                'verbose_name': 'Usd',
                'verbose_name_plural': 'Usds',
            },
        ),
        migrations.CreateModel(
            name='ingresos_eur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ef', models.CharField(max_length=10)),
                ('tc', models.CharField(max_length=10)),
                ('td', models.CharField(max_length=10)),
                ('pm', models.CharField(max_length=10)),
                ('nc', models.CharField(max_length=10)),
                ('ti_eur', models.CharField(max_length=20)),
                ('conversion', models.CharField(max_length=30)),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now_add=True)),
                ('caja_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.caja')),
                ('tasa_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tasa')),
                ('tienda_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tienda')),
            ],
            options={
                'verbose_name': 'Eur',
                'verbose_name_plural': 'Eurs',
            },
        ),
        migrations.CreateModel(
            name='ingresos_bs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_caja', models.CharField(default='', max_length=4)),
                ('ef', models.CharField(max_length=10)),
                ('td', models.CharField(max_length=10)),
                ('tc', models.CharField(max_length=10)),
                ('pm', models.CharField(max_length=10)),
                ('nc', models.CharField(max_length=10)),
                ('ti_bs', models.CharField(max_length=20)),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now_add=True)),
                ('tienda_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tienda')),
            ],
            options={
                'verbose_name': 'Bs',
                'verbose_name_plural': 'Bss',
            },
        ),
        migrations.CreateModel(
            name='arqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cii', models.CharField(max_length=30)),
                ('sg', models.CharField(max_length=30)),
                ('dt', models.CharField(max_length=30)),
                ('cif', models.CharField(max_length=30)),
                ('vd', models.CharField(max_length=30)),
                ('nota', models.CharField(max_length=120)),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now_add=True)),
                ('caja_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.caja')),
                ('ingreso_bs_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ArqueoCaja.ingresos_bs')),
                ('ingreso_eur_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ArqueoCaja.ingresos_eur')),
                ('ingreso_usd_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ArqueoCaja.ingresos_usd')),
                ('tienda_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tienda')),
            ],
            options={
                'verbose_name': 'Arq',
                'verbose_name_plural': 'Arqs',
            },
        ),
    ]
