# Generated by Django 3.2.9 on 2023-05-31 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0004_auto_20230530_2358'),
        ('ArqueoCaja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueo',
            name='caja_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.caja'),
        ),
        migrations.AlterField(
            model_name='arqueo',
            name='ingreso_bs_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ArqueoCaja.ingresos_bs'),
        ),
        migrations.AlterField(
            model_name='arqueo',
            name='ingreso_eur_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ArqueoCaja.ingresos_eur'),
        ),
        migrations.AlterField(
            model_name='arqueo',
            name='ingreso_usd_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ArqueoCaja.ingresos_usd'),
        ),
        migrations.AlterField(
            model_name='arqueo',
            name='tienda_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tienda'),
        ),
        migrations.AlterField(
            model_name='ingresos_bs',
            name='codigo_caja',
            field=models.CharField(default=1, max_length=4),
        ),
        migrations.AlterField(
            model_name='ingresos_bs',
            name='tienda_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tienda'),
        ),
        migrations.AlterField(
            model_name='ingresos_eur',
            name='caja_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.caja'),
        ),
        migrations.AlterField(
            model_name='ingresos_eur',
            name='tasa_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tasa'),
        ),
        migrations.AlterField(
            model_name='ingresos_eur',
            name='tienda_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tienda'),
        ),
        migrations.AlterField(
            model_name='ingresos_usd',
            name='caja_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.caja'),
        ),
        migrations.AlterField(
            model_name='ingresos_usd',
            name='tasa_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tasa'),
        ),
        migrations.AlterField(
            model_name='ingresos_usd',
            name='tienda_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tienda'),
        ),
    ]
