# Generated by Django 3.2.9 on 2023-06-06 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0004_auto_20230530_2358'),
        ('ArqueoCaja', '0003_auto_20230605_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresos_bs',
            name='codigo_caja',
        ),
        migrations.AddField(
            model_name='ingresos_bs',
            name='caja_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.caja'),
        ),
    ]
