# Generated by Django 3.2.9 on 2023-06-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArqueoCaja', '0004_auto_20230605_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueo',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ingresos_bs',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ingresos_eur',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ingresos_usd',
            name='created',
            field=models.DateField(),
        ),
    ]
