# Generated by Django 3.2.9 on 2023-06-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArqueoCaja', '0005_auto_20230606_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingresos_bs',
            old_name='ef',
            new_name='ef_bs',
        ),
        migrations.RenameField(
            model_name='ingresos_bs',
            old_name='nc',
            new_name='nc_bs',
        ),
        migrations.RenameField(
            model_name='ingresos_bs',
            old_name='pm',
            new_name='pm_bs',
        ),
        migrations.RenameField(
            model_name='ingresos_bs',
            old_name='tc',
            new_name='tc_bs',
        ),
        migrations.RenameField(
            model_name='ingresos_bs',
            old_name='td',
            new_name='td_bs',
        ),
        migrations.RenameField(
            model_name='ingresos_eur',
            old_name='conversion',
            new_name='conversion_eur',
        ),
        migrations.RenameField(
            model_name='ingresos_eur',
            old_name='ef',
            new_name='ef_eur',
        ),
        migrations.RenameField(
            model_name='ingresos_eur',
            old_name='nc',
            new_name='nc_eur',
        ),
        migrations.RenameField(
            model_name='ingresos_eur',
            old_name='pm',
            new_name='pm_eur',
        ),
        migrations.RenameField(
            model_name='ingresos_eur',
            old_name='tc',
            new_name='tc_eur',
        ),
        migrations.RenameField(
            model_name='ingresos_eur',
            old_name='td',
            new_name='td_eur',
        ),
        migrations.RenameField(
            model_name='ingresos_usd',
            old_name='conversion',
            new_name='conversion_usd',
        ),
        migrations.RenameField(
            model_name='ingresos_usd',
            old_name='ef',
            new_name='ef_usd',
        ),
        migrations.RenameField(
            model_name='ingresos_usd',
            old_name='nc',
            new_name='nc_usd',
        ),
        migrations.RenameField(
            model_name='ingresos_usd',
            old_name='pm',
            new_name='pm_usd',
        ),
        migrations.RenameField(
            model_name='ingresos_usd',
            old_name='tc',
            new_name='tc_usd',
        ),
        migrations.RenameField(
            model_name='ingresos_usd',
            old_name='td',
            new_name='td_usd',
        ),
        migrations.AddField(
            model_name='arqueo',
            name='procesado',
            field=models.BooleanField(default=False),
        ),
    ]
