# Generated by Django 3.2.9 on 2023-06-06 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0004_auto_20230530_2358'),
        ('ArqueoCaja', '0006_auto_20230606_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ef_bs', models.CharField(max_length=10)),
                ('td_bs', models.CharField(max_length=10)),
                ('tc_bs', models.CharField(max_length=10)),
                ('pm_bs', models.CharField(max_length=10)),
                ('nc_bs', models.CharField(max_length=10)),
                ('ti_bs', models.CharField(max_length=20)),
                ('ef_usd', models.CharField(max_length=10)),
                ('tc_usd', models.CharField(max_length=10)),
                ('td_usd', models.CharField(max_length=10)),
                ('pm_usd', models.CharField(max_length=10)),
                ('nc_usd', models.CharField(max_length=10)),
                ('ti_usd', models.CharField(max_length=20)),
                ('conversion_usd', models.CharField(max_length=20)),
                ('ef_eur', models.CharField(max_length=10)),
                ('tc_eur', models.CharField(max_length=10)),
                ('td_eur', models.CharField(max_length=10)),
                ('pm_eur', models.CharField(max_length=10)),
                ('nc_eur', models.CharField(max_length=10)),
                ('ti_eur', models.CharField(max_length=20)),
                ('conversion_eur', models.CharField(max_length=30)),
                ('created', models.DateField()),
                ('update', models.DateField(auto_now_add=True)),
                ('caja_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.caja')),
                ('tasa_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tasa')),
                ('tienda_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tienda')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
        migrations.RemoveField(
            model_name='ingresos_eur',
            name='caja_id',
        ),
        migrations.RemoveField(
            model_name='ingresos_eur',
            name='tasa_id',
        ),
        migrations.RemoveField(
            model_name='ingresos_eur',
            name='tienda_id',
        ),
        migrations.RemoveField(
            model_name='ingresos_usd',
            name='caja_id',
        ),
        migrations.RemoveField(
            model_name='ingresos_usd',
            name='tasa_id',
        ),
        migrations.RemoveField(
            model_name='ingresos_usd',
            name='tienda_id',
        ),
        migrations.AlterModelOptions(
            name='arqueo',
            options={'verbose_name': 'Arqueo', 'verbose_name_plural': 'Arqueos'},
        ),
        migrations.RemoveField(
            model_name='arqueo',
            name='ingreso_bs_id',
        ),
        migrations.RemoveField(
            model_name='arqueo',
            name='ingreso_eur_id',
        ),
        migrations.RemoveField(
            model_name='arqueo',
            name='ingreso_usd_id',
        ),
        migrations.DeleteModel(
            name='ingresos_bs',
        ),
        migrations.DeleteModel(
            name='ingresos_eur',
        ),
        migrations.DeleteModel(
            name='ingresos_usd',
        ),
        migrations.AddField(
            model_name='arqueo',
            name='ingreso_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ArqueoCaja.ingresos'),
        ),
    ]
