# Generated by Django 3.2.9 on 2023-06-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArqueoCaja', '0007_auto_20230606_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='tif',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='conversion_eur',
            field=models.CharField(max_length=20),
        ),
    ]
