# Generated by Django 3.2.9 on 2023-06-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArqueoCaja', '0008_auto_20230606_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresos',
            name='conversion_eur',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='ef_eur',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='nc_eur',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='pm_eur',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='tc_eur',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='td_eur',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='ti_eur',
        ),
        migrations.AddField(
            model_name='ingresos',
            name='nota',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
