# Generated by Django 3.2.9 on 2023-06-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArqueoCaja', '0010_auto_20230617_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arqueo',
            name='ingreso_id',
        ),
        migrations.DeleteModel(
            name='ingresos',
        ),
    ]
