# Generated by Django 3.2.9 on 2023-06-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArqueoCaja', '0015_remove_arqueo_venta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueo',
            name='procesado',
            field=models.BooleanField(),
        ),
    ]
