# Generated by Django 4.2.4 on 2023-12-21 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0005_comunicado'),
        ('ArqueoCaja', '0018_remove_arqueo_venta_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arqueo',
            old_name='caja_id',
            new_name='caja',
        ),
        migrations.RenameField(
            model_name='arqueo',
            old_name='vd',
            new_name='cierre',
        ),
        migrations.RenameField(
            model_name='arqueo',
            old_name='tienda_id',
            new_name='tienda',
        ),
        migrations.AddField(
            model_name='arqueo',
            name='dv',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arqueo',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ef_bs', models.CharField(max_length=10)),
                ('ef_usd', models.CharField(max_length=10)),
                ('ef_eur', models.CharField(max_length=10)),
                ('td_bs', models.CharField(max_length=10)),
                ('td_usd', models.CharField(max_length=10)),
                ('tc_bs', models.CharField(max_length=10)),
                ('tr_bs', models.CharField(max_length=10)),
                ('tr_zll', models.CharField(max_length=10)),
                ('pm_bs', models.CharField(max_length=10)),
                ('ti_bs', models.CharField(max_length=20)),
                ('ti_usd', models.CharField(max_length=20)),
                ('ti_eur', models.CharField(max_length=20)),
                ('ti_zll', models.CharField(max_length=20)),
                ('tasa', models.CharField(max_length=4)),
                ('ti', models.CharField(max_length=20)),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.caja')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tienda')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
        migrations.AddField(
            model_name='arqueo',
            name='ingresos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ArqueoCaja.ingresos'),
            preserve_default=False,
        ),
    ]
