# Generated by Django 4.2.4 on 2023-12-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArqueoCaja', '0019_rename_caja_id_arqueo_caja_rename_vd_arqueo_cierre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arqueo',
            old_name='cif',
            new_name='ti',
        ),
        migrations.RemoveField(
            model_name='arqueo',
            name='cii',
        ),
        migrations.RemoveField(
            model_name='arqueo',
            name='ingresos',
        ),
        migrations.AddField(
            model_name='arqueo',
            name='ef_bs',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arqueo',
            name='ef_eur',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arqueo',
            name='ef_usd',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arqueo',
            name='pm_bs',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arqueo',
            name='tasa',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arqueo',
            name='tc_bs',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arqueo',
            name='td_bs',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arqueo',
            name='td_usd',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arqueo',
            name='ti_bs',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arqueo',
            name='ti_eur',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arqueo',
            name='ti_usd',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arqueo',
            name='ti_zll',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arqueo',
            name='tr_bs',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arqueo',
            name='tr_zll',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ingresos',
        ),
    ]
