# Generated by Django 4.2.4 on 2023-12-22 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAC', '0006_rename_tienda_id_caja_tienda_and_more'),
        ('ArqueoCaja', '0020_rename_cif_arqueo_ti_remove_arqueo_cii_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueo',
            name='tasa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebAC.tasa'),
        ),
    ]
