# Generated by Django 4.2.4 on 2023-12-22 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArqueoCaja', '0021_alter_arqueo_tasa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arqueo',
            name='tasa',
        ),
    ]
