# Generated by Django 4.2.4 on 2024-01-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArqueoCaja', '0023_arqueo_tasadolar_arqueo_tasaeuro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arqueo',
            old_name='td_usd',
            new_name='gt',
        ),
        migrations.RemoveField(
            model_name='arqueo',
            name='sg',
        ),
        migrations.RemoveField(
            model_name='arqueo',
            name='ti',
        ),
        migrations.AddField(
            model_name='arqueo',
            name='tc_usd',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arqueo',
            name='vn_bs',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arqueo',
            name='vn_usd',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arqueo',
            name='dt',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='arqueo',
            name='dv',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='arqueo',
            name='ft',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='arqueo',
            name='nota',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='arqueo',
            name='st',
            field=models.CharField(max_length=10),
        ),
    ]
