# Generated by Django 4.2.4 on 2024-01-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArqueoCaja', '0024_rename_td_usd_arqueo_gt_remove_arqueo_sg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueo',
            name='fi',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
