# Generated by Django 4.2.4 on 2024-01-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArqueoCaja', '0025_arqueo_fi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueo',
            name='created',
            field=models.CharField(max_length=10),
        ),
    ]
