# Generated by Django 4.2.4 on 2024-01-15 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArqueoCaja', '0026_alter_arqueo_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arqueo',
            old_name='caja',
            new_name='codigo_caja',
        ),
        migrations.RenameField(
            model_name='arqueo',
            old_name='tienda',
            new_name='codigo_tienda',
        ),
    ]
