# Generated by Django 4.2.4 on 2024-01-15 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArqueoCaja', '0027_rename_caja_arqueo_codigo_caja_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arqueo',
            old_name='codigo_caja',
            new_name='caja',
        ),
        migrations.RenameField(
            model_name='arqueo',
            old_name='codigo_tienda',
            new_name='tienda',
        ),
    ]
