# Generated by Django 4.2.4 on 2024-01-29 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArqueoCaja', '0028_rename_codigo_caja_arqueo_caja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arqueo',
            name='tasaDolar',
        ),
    ]
