# Generated by Django 4.2.4 on 2024-01-29 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArqueoCaja', '0030_arqueo_tasadivisa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arqueo',
            name='tasaEuro',
        ),
    ]
