# Generated by Django 4.2.4 on 2024-01-29 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArqueoCaja', '0031_remove_arqueo_tasaeuro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arqueo',
            old_name='ft',
            new_name='df',
        ),
        migrations.RemoveField(
            model_name='arqueo',
            name='st',
        ),
    ]
